version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  rspec:
    docker:
      - image: cimg/ruby:2.7.6
    resource_class: small
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Database setup
          command: |
            run: bundle exec rails db:create
            run: bundle exec rails db:migrate
      - run:
          name: Run rspec
          command: bundle exec rspec

  rubocop:
    docker:
      - image: cimg/ruby:2.7.6
    resource_class: small
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Run rubocop
          command: bundle exec rubocop --require rubocop-airbnb

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - rspec
      - rubocop
